version: '2'
services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./exercism-go:/go/src/github.com/pmuens/exercism-go
    working_dir: /go/src/github.com/pmuens/exercism-go/exercises
