#!/bin/bash

if [ -d exercism-ecmascript ]; then
  echo "Checking for updates..."
  cd exercism-ecmascript
  git fetch origin
  cd ..
else
  git clone https://github.com/exercism/xecmascript ./exercism-ecmascript
fi;

docker-compose run ecmascript bash
