#!/bin/bash

if [ -d exercism-rust ]; then
  echo "Checking for updates..."
  cd exercism-rust
  git fetch origin
  cd ..
else
  git clone https://github.com/exercism/xrust ./exercism-rust
fi;

docker-compose run rust bash
